services:
  ldap_server:
    extends:
      file: ./authentication/compose.yml
      service: ldap_server
  ldap_admin:
    extends:
      file: ./authentication/compose.yml
      service: ldap_admin
  shinyproxy:
    extends:
      file: ./shinyproxy/compose.yml
      service: shinyproxy
    depends_on:
      ldap_server:
        condition: service_healthy
  database:
    extends:
      file: ./monitoring/compose.yml
      service: database
  grafana:
    attach: false
    extends:
      file: ./monitoring/compose.yml
      service: grafana
  api_dispatcher:
    extends:
      file: ./services/compose.yml
      service: api_dispatcher
  fastapi:
    extends:
      file: ./services/compose.yml
      service: fastapi
  oxygen:
    extends:
      file: ./services/compose.yml
      service: oxygen
  plumber:
    extends:
      file: ./services/compose.yml
      service: plumber
  gin:
    extends:
      file: ./services/compose.yml
      service: gin
  express:
    extends:
      file: ./services/compose.yml
      service: express
  spring:
    extends:
      file: ./services/compose.yml
      service: spring

networks:
  ssd-network:
    name: ssd-network
