services:
  ldap_server:
    profiles: [auth]
    env_file: [variables.env]
    extends:
      file: ./authentication/compose.yml
      service: ldap_server
  ldap_admin:
    profiles: [auth]
    env_file: [variables.env]
    extends:
      file: ./authentication/compose.yml
      service: ldap_admin
    ports:
      - 6480:80 
  shinyproxy:
    profiles: [shinyproxy]
    env_file: [variables.env]
    extends:
      file: ./shinyproxy/compose.yml
      service: shinyproxy
    depends_on:
      ldap_server:
        condition: service_healthy
      monitoring_db:
        condition: service_healthy
    volumes:
    - .logs/shinyproxy:/var/log/shinyproxy
    ports:
      - 8080:8080
  monitoring_db:
    profiles: [monitoring]
    env_file: [variables.env]
    extends:
      file: ./monitoring/compose.yml
      service: monitoring_db
  grafana:
    profiles: [monitoring]
    env_file: [variables.env]
    attach: false
    extends:
      file: ./monitoring/compose.yml
      service: grafana
    ports:
      - 3000:3000
  loki:
    profiles: [monitoring]
    env_file: [variables.env]
    attach: false
    extends:
      file: ./monitoring/compose.yml
      service: loki
  alloy:
    profiles: [monitoring]
    env_file: [variables.env]
    attach: false
    extends:
      file: ./monitoring/compose.yml
      service: alloy
    volumes:
      - .logs:/var/log
  api_dispatcher:
    profiles: [services]
    env_file: [variables.env]
    extends:
      file: ./services/compose.yml
      service: api_dispatcher
    depends_on:
      monitoring_db:
        condition: service_healthy
  fastapi:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: fastapi
  oxygen:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: oxygen
  plumber:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: plumber
  gin:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: gin
  express:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: express
  spring:
    profiles: [services]
    extends:
      file: ./services/compose.yml
      service: spring
  cache_db:
    profiles: [cache]
    env_file: [variables.env]
    extends:
      file: ./cache/compose.yml
      service: cache_db

networks:
  ssd-network:
    name: ssd-network
