services:
  ldap_server:
    extends:
      file: ./authentication/compose.yml
      service: ldap_server
  ldap_admin:
    extends:
      file: ./authentication/compose.yml
      service: ldap_admin
  shinyproxy:
    extends:
      file: ./shinyproxy/compose.yml
      service: shinyproxy
    depends_on:
      ldap_server:
        condition: service_healthy
  telemetry_api:
    extends:
      file: ./monitoring/compose.yml
      service: telemetry_api
  grafana:
    attach: false
    extends:
      file: ./monitoring/compose.yml
      service: grafana
  class_service:
    extends:
      file: ./services/compose.yml
      service: class_service

networks:
  ssd-network:
    name: ssd-network
