version: '3'

dotenv: [.env, .env.example]

tasks:

  default:
    silent: true
    cmd: task --list

  shinyproxy_env_file:
    deps:
      - shinyproxy_env_file_windows
      - shinyproxy_env_file_unix

  build:
    desc: Build all docker images from the bake file
    deps: [task: shinyproxy_env_file]
    cmd: docker buildx bake

  start:
    desc: Start all compose services
    aliases: [up]
    env:
      COMPOSE_PROFILES: auth,shinyproxy,monitoring,services,cache
    cmd: docker-compose up {{.CLI_ARGS}}

  start-without-cache:
    desc: Start all compose profiles except for cache
    env:
      COMPOSE_PROFILES: auth,shinyproxy,monitoring,services
    cmd: docker-compose up

  start-without-services:
    desc: Start all compose profiles except for cache and services
    env:
      COMPOSE_PROFILES: auth,shinyproxy,monitoring
    cmd: docker-compose up

  clean-docker:
    desc: Delete all docker resources
    prompt: This will delete absolutely all docker resources (container, images, volumes, builds). Do you want to proceed?
    cmds:
      - docker ps -qa || docker stop $(docker ps -qa)
      - docker ps -qa || docker rm $(docker ps -qa) -f
      - docker images -q || docker rmi $(docker images -q) -f
      - docker volume ls -qf dangling=true || docker volume rm $(docker volume ls -qf dangling=true) -f
      - docker system prune -fa
      - docker volume prune -fa
      - docker buildx prune -fa
      - docker buildx history rm --all
      - docker buildx du

  clean-volumes:
    desc: Delete all folders that are used to persist docker container data
    deps: [clean-volumes-windows, clean-volumes-unix]

  # --- Internal Commands ---

  shinyproxy_env_file_windows:
    internal: true
    platforms: [windows]
    cmd: Copy-Item "variables.env" -Destination "./shinyproxy/proxy/variables.env"

  shinyproxy_env_file_unix:
    internal: true
    platforms: [darwin, linux]
    cmd: cp variables.env ./shinyproxy/proxy/variables.env

  clean-volumes-windows:
    internal: true
    platforms: [windows]
    prompt: Do you really want to delete these folders?
    cmds:
      - Remove-Item -LiteralPath "authentication/ldap_server/data" -Force -Recurse
      - Remove-Item -LiteralPath "monitoring/database/data" -Force -Recurse
  
  clean-volumes-unix:
    internal: true
    platforms: [darwin, linux]
    prompt: Do you really want to delete these folders?
    cmds:
      - rm -rf authentication/ldap_server/data
      - rm -rf monitoring/database/data
