server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: shinyproxy-logs
  static_configs:
  - targets: [ 'shinyproxy' ]
    labels:
      job: proxy_logs
      __path__:  /var/log/shinyproxy/proxy-logs/*.log
  # - targets: [ 'shinyproxy' ]
  #   labels:
  #     job: container_logs
  #     __path__:  /var/log/shinyproxy/container-logs/*.log
