proxy:
  title: Shiny System Design
  landing-page: SingleApp
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  admin-groups: admins
  ldap:
    url: "ldap://ldap_server/dc=ldapusermanager,dc=org"
    manager-dn: cn=admin,dc=ldapusermanager,dc=org
    manager-password: admin
    user-search-filter: (uid={0})
    user-search-base: ou=accounts
    group-search-filter: (memberUid={1})
    group-search-base: ou=groups
  docker:
    internal-networking: true
    image-pull-policy: Never
  specs:
    - id: penguins_explorer
      display-name: Penguins Explorer
      description: Simple visualizaion of the penguins dataset.
      access-groups: [ admins, users ]
      container-cmd: [ "R", "-e", "shiny::runApp(host = '0.0.0.0', port = 3838L)" ]
      container-image: shiny-system-design/shinyapp:latest
      container-network-connections: [ ssd-network ]
  usage-stats-url: jdbc:postgresql://db_monitoring:5432/postgres?user=postgres&password=postgres&ssl=false
  container-log-path: /var/log/shinyproxy/container-logs

logging:
  file:
    path: /var/log/shinyproxy/proxy-logs
