services:
  database:
    container_name: database
    image: shiny-system-design/database:latest
    pull_policy: never
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - ssd-network
  grafana:
    container_name: grafana
    image: shiny-system-design/grafana:latest
    pull_policy: never
    restart: always
    ports:
      - 3000:3000
    networks:
      - ssd-network
