services:
  monitoring_db:
    platform: linux/amd64
    container_name: monitoring_db
    image: shiny-system-design/monitoring_db:latest
    pull_policy: never
    restart: always
    user: postgres
    volumes:
      - ./monitoring_db/data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - ssd-network
  grafana:
    platform: linux/amd64
    container_name: grafana
    image: shiny-system-design/grafana:latest
    pull_policy: never
    restart: always
    networks:
      - ssd-network
  loki:
    platform: linux/amd64
    container_name: loki
    image: shiny-system-design/loki:latest
    pull_policy: never
    networks:
      - ssd-network
  alloy:
    platform: linux/amd64
    container_name: alloy
    image: shiny-system-design/alloy:latest
    pull_policy: never
    networks:
      - ssd-network
