services:
  monitoring_db:
    container_name: monitoring_db
    image: shiny-system-design/monitoring_db:latest
    pull_policy: never
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./monitoring_db/data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - ssd-network
  grafana:
    container_name: grafana
    image: shiny-system-design/grafana:latest
    pull_policy: never
    restart: always
    ports:
      - 3000:3000
    networks:
      - ssd-network
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/config.yaml:/etc/loki/loki-config.yaml
    networks:
      - ssd-network
  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    volumes:
      - ./alloy/config.alloy:/mnt/config/config.alloy
    ports:
      - 12345:12345
    command: run --server.http.listen-addr=0.0.0.0:12345 /mnt/config/config.alloy
    networks:
      - ssd-network
