services:
  telemetry_api:
    container_name: telemetry_api
    image: shiny-system-design/telemetry_api:latest
    pull_policy: never
    restart: always
    volumes:
      - ./telemetry/logs:/app/logs
    networks:
      - ssd-network
  grafana:
    container_name: grafana
    image: shiny-system-design/grafana:latest
    pull_policy: never
    restart: always
    ports:
      - 3000:3000
    networks:
      - ssd-network
