services:
  shinyproxy:
    platform: linux/amd64
    container_name: shinyproxy
    image: shiny-system-design/shinyproxy:latest
    pull_policy: never
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ssd-network
