services:
  api_dispatcher:
    container_name: api_dispatcher
    image: shiny-system-design/api_dispatcher:latest
    pull_policy: never
    networks:
      - ssd-network
  fastapi:
    container_name: fastapi
    image: shiny-system-design/fastapi:latest
    pull_policy: never
    networks:
      - ssd-network
  oxygen:
    container_name: oxygen
    image: shiny-system-design/oxygen:latest
    pull_policy: never
    networks:
      - ssd-network
  plumber:
    container_name: plumber
    image: shiny-system-design/plumber:latest
    pull_policy: never
    networks:
      - ssd-network
