{
 "title": "ApiDispatcher",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH timerange AS (\n  SELECT date_trunc('minute', series) as time\n  FROM generate_series($__timeFrom(), $__timeTo(), '1 minute'::interval) series\n),\nevents_per_minute as (\n  select date_trunc('minute', created_at) as time, count(*) as n\n  from api_dispatcher_log \n  GROUP BY 1\n)\n\nselect a.time, coalesce(b.n, 0) as n\nfrom timerange a left join events_per_minute b on a.time=b.time\norder by a.time"
    }
   ]
  },
  {
   "title": "Top API Targets by requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select header as api_target, count(*) as n\nfrom api_dispatcher_log \nwhere $__timeFilter(created_at)\ngroup by 1\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Average Request Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select header as api_target, avg(process_time) as avg_process_time\nfrom api_dispatcher_log \nwhere $__timeFilter(created_at)\ngroup by 1\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with ok_responses as (\n  select * from api_dispatcher_log \n  where $__timeFilter(created_at) and status_code = 200\n),\n\nbad_responses as (\n  select * from api_dispatcher_log \n  where $__timeFilter(created_at) and status_code <> 200\n)\n\nselect 'OK' as status, count(*) as n\nfrom ok_responses\nunion all\nselect 'BAD' as status, count(*) as n\nfrom bad_responses\n"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from api_dispatcher_log where $__timeFilter(created_at) order by created_at desc\n"
    }
   ]
  }
 ]
}