{
 "title": "ShinyProxy Dashboard",
 "description": "Logs and Metrics of the ShinyProxy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Applications",
   "type": "timeseries",
   "description": "Cumulative ProxyStart - ProxyStop over time intervals.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH timerange AS (\n  SELECT date_trunc('minute', series) as time\n  FROM generate_series($__timeFrom(), $__timeTo(), '1 minute'::interval) series\n),\n\nproxy_starts AS (\n  select date_trunc('minute', event_time) as time, 1 as action\n  from event\n  where type = 'ProxyStart'\n),\n\nproxy_starts_agg AS (\n  select time, sum(action) as action\n  from proxy_starts\n  group by time\n),\n\nproxy_stops AS (\n  select date_trunc('minute', event_time) as time, 1 as action\n  from event\n  where type = 'ProxyStop'\n),\n\nproxy_stops_agg AS (\n  select time, sum(action) as action\n  from proxy_stops\n  group by time\n),\n\naggregated AS (\n  SELECT\n    $__timeGroup(a.time, 1m) as time,\n    SUM(COALESCE(b.action, 0)) as proxy_starts,\n    SUM(COALESCE(c.action, 0)) as proxy_stops\n  FROM timerange a\n  LEFT JOIN proxy_starts_agg b ON a.time = b.time\n  LEFT JOIN proxy_stops_agg c ON a.time = c.time\n  GROUP BY 1\n)\n\nSELECT\n  time,\n  SUM(proxy_starts) OVER(ORDER BY time) - SUM(proxy_stops) OVER(ORDER BY time) as running\nFROM aggregated\n"
    }
   ]
  },
  {
   "title": "Top Users by Logins",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  username,\n  COUNT(*) AS event_count\nFROM event\nWHERE $__timeFilter(event_time)\n  AND type = 'Login'\nGROUP BY username\nORDER BY event_count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "ShinyProxy Log",
   "type": "table",
   "description": "All logs of the ShinyProxy instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select *\nfrom event\nwhere 1 = 1\n  and event_time BETWEEN $__timeFrom() and $__timeTo()\norder by event_time desc\n"
    }
   ]
  }
 ]
}