{
 "title": "ShinyTelemetry",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Session Duration, minutes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with timerange as (\n  select date_trunc('day', series) as time\n  from generate_series($__timeFrom(), $__timeTo(), '1 day'::interval) series\n),\nlogins as (\n  select session, min(time) as time\n  from event_log\n  where type = 'login'\n  group by session\n),\nlogouts as (\n  select session, min(time) as time\n  from event_log\n  where type = 'logout'\n  group by session\n),\navg_session_duration as (\n  select date_trunc('day', b.time) as time, extract(epoch from avg((b.time - a.time))) / 60 as session_duration\n  from logins a\n  join logouts b on a.session = b.session\n  group by 1\n)\n\nselect a.time, coalesce(b.session_duration, 0) as avg_session_duration_minutes\nfrom timerange a\nleft join avg_session_duration b\non a.time = b.time\n"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "with timerange as (\n  select date_trunc('day', series) as time\n  from generate_series($__timeFrom(), $__timeTo(), '1 day'::interval) series\n),\nlogins as (\n  select session, min(time) as time\n  from event_log\n  where type = 'login'\n  group by session\n),\nlogouts as (\n  select session, min(time) as time\n  from event_log\n  where type = 'logout'\n  group by session\n),\nusersessions as (\n  select distinct session, details::json->'username'->>0 as username\n  from event_log \n  where type = 'login'\n)\n\nselect\n  date_trunc('second', a.time) as start,\n  date_trunc('second', b.time) as end,\n  a.session as session_id,\n  c.username,\n  (b.time - a.time) as session_duration\nfrom logins a\njoin logouts b on a.session = b.session\njoin usersessions c on a.session = c.session\norder by 1 desc;"
    }
   ]
  },
  {
   "title": "Most Requested APIs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- select * from event_log order by time desc;\n\n-- WITH timerange AS (\n--   SELECT date_trunc('minute', series) as time\n--   FROM generate_series($__timeFrom(), $__timeTo(), '1 minute'::interval) series\n-- ),\n\n-- inputs_agg AS (\n--   select date_trunc('minute', time) as time, count(*) as n\n--   from event_log\n--   where type = 'input'\n--   GROUP BY 1\n-- )\n\n-- select a.time, coalesce(b.n, 0) as n\n-- from timerange a left join inputs_agg b\n-- on a.time = b.time;\n\nwith input_values as (\nselect\n  details :: json -> 'id' ->> 0 as input_id,\n  details :: json -> 'value' ->> 0 as input_value\nfrom\n  event_log\nwhere\n  type = 'input'\n)\n\nselect input_value as api_target, count(*) as n\nfrom input_values\nwhere input_id = 'api_target'\ngroup by input_value\norder by 2 desc;\n"
    }
   ]
  },
  {
   "title": "User's Browser",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  details :: json -> 'value' ->> 0 as browser,\n  count (*) as n\nfrom\n  event_log\nwhere\n  type = 'browser'\ngroup by\n  1"
    }
   ]
  },
  {
   "title": "Total Inputs per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "-- select * from event_log order by time desc;\n\nWITH timerange AS (\n  SELECT date_trunc('day', series) as time\n  FROM generate_series($__timeFrom(), $__timeTo(), '1 day'::interval) series\n),\n\ninputs_agg AS (\n  select date_trunc('day', time) as time, count(*) as n\n  from event_log\n  where type = 'input'\n  GROUP BY 1\n)\n\nselect a.time, coalesce(b.n, 0) as n\nfrom timerange a left join inputs_agg b\non a.time = b.time;"
    }
   ]
  },
  {
   "title": "Raw Telemetry Log",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select * from event_log order by time desc;"
    }
   ]
  }
 ]
}