apiVersion: 1

datasources:
  - id: 1 
    name: monitoring-database
    type: grafana-postgresql-datasource
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg
    access: proxy
    url: monitoring_db:5432
    user: postgres
    secureJsonData:
      password: postgres
    basicAuth: false
    isDefault: true
    jsonData: 
      connMaxLifetime: 14400
      database: postgres
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      sslmode: disable
    readOnly: false
  - id: 2
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false