services: 
  ldap_server:
    platform: linux/amd64
    container_name: ldap_server
    image: shiny-system-design/ldap_server:latest
    pull_policy: never
    networks:
      - ssd-network
    volumes:
      - ./ldap_server/data/var/lib/ldap:/var/lib/ldap
      - ./ldap_server/data/etc/ldap/slapd.d:/etc/ldap/slapd.d
    healthcheck:
      test: ["CMD", "cat", "/run/slapd/slapd.pid"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s


  ldap_admin:
    platform: linux/amd64
    container_name: ldap_admin
    image: shiny-system-design/ldap_admin:latest
    pull_policy: never
    networks:
      - ssd-network
    depends_on:
      ldap_server:
        condition: service_healthy
